// SPDX-License-Identifier: AGPL-3.0-only
import { build } from 'esbuild'
import { mkdir, writeFile, readFile, readdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const root = fileURLToPath(new URL('../', import.meta.url))
const result = await build({
  absWorkingDir: root, entryPoints: ['src/components/lyrics/web/index.ts'],
  bundle: true, write: false, outdir: 'lyrics-bundle', format: 'iife',
  metafile: true, platform: 'browser', target: ['safari15.4'], minify: true, legalComments: 'inline',
})
const js = result.outputFiles.find(file => file.path.endsWith('.js')).text.replace(/<\/script/gi, '<\\/script')
const css = result.outputFiles.find(file => file.path.endsWith('.css')).text.replace(/<\/style/gi, '<\\/style')
const packages = new Map()
for (const input of Object.keys(result.metafile.inputs)) {
  if (!input.startsWith('node_modules/')) continue
  const parts = input.split('/')
  const dir = parts[1].startsWith('@') ? parts.slice(0, 3).join('/') : parts.slice(0, 2).join('/')
  if (packages.has(dir)) continue
  const info = JSON.parse(await readFile(path.join(root, dir, 'package.json'), 'utf8'))
  const filenames = (await readdir(path.join(root, dir))).filter(name => /^(licen[sc]e|copying)(\.|$)/i.test(name))
  const texts = await Promise.all(filenames.map(name => readFile(path.join(root, dir, name), 'utf8')))
  packages.set(dir, `${info.name} ${info.version} (${info.license})\n${texts.join('\n')}`)
}
const notices = `AMLL integration: AGPL-3.0-only. Original application: MIT.\nCorresponding source: https://github.com/xuys2025/joy-music-mobile/tree/feature/applemusic-lyrics\n${await readFile(path.join(root, 'licenses/Original-MIT.txt'), 'utf8')}\n${[...packages.values()].join('\n\n')}`
const html = `<!doctype html><html data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'"><style>${css}</style></head><body><main id="lyrics" aria-label="同步歌词"></main><script>${js}</script><script type="text/plain" id="open-source-licenses">${notices.replace(/<\/script/gi, '<\\/script')}</script></body></html>`
const output = path.join(root, 'src/components/lyrics/generated')
await mkdir(output, { recursive: true })
await writeFile(path.join(output, 'lyricsHtml.ts'), `// Generated by npm run lyrics:build. Do not edit.\nexport const lyricsHtml: string = ${JSON.stringify(html)}\n`)
console.log(`Bundled local AMLL renderer: ${Math.round(Buffer.byteLength(html) / 1024)} KiB; ${packages.size} dependency notices`)
